apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: nb1c0z9wn-nodejs 
  janus-idp.io/tekton: nb1c0z9wn-nodejs
  backstage.io/kubernetes-id: nb1c0z9wn-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: nb1c0z9wn-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml