apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nb1c0z9wn-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:172592ff1f5c10fc82a36fb44607182614f64f2b@sha256:cf5219174f5e0ec11bd93efd07e15b1d84b448bc0ff9b58855e407db362ffc83
          name: container-image
