apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nb1c0z9wn-nodejs
  janus-idp.io/tekton: nb1c0z9wn-nodejs
  backstage.io/kubernetes-id: nb1c0z9wn-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: nb1c0z9wn-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
